### PR TITLE
Adds CoC

### PR DESCRIPTION
**Pull request by garethellis36**
Taken from PHPSW website

### CODE REVIEW

**Comment by garethellis36** [comment]
@mcidahechi @martindilling @liquorvicar  @olorton  any comments?

**Review by olorton — COMMENTED** [review]
Are we likely to have any future meetups held at WO? If so I should probably be added as an organiser.

**Comment by garethellis36** [comment]
I don't know but I'm more than happy to list you as an organiser. :+1:

**Comment by garethellis36** [comment]
Done

**Comment by olorton** [comment]
Approved from me.

**Comment by mcidahechi** [comment]
Yes this all makes sense.

**Comment by martindilling** [comment]
Looks good to me :)

**Pull request merged**
